---
title: "Create metadata matrix"
author: "Louisa Hadj Abed"
date: "04/06/2022"
output: html_document
---

This script creates a metadata matrix based on a given count matrix and based on given column names.


```{r , echo=TRUE, warning=FALSE}
devtools::install_github("TeamPerie/CellDestiny", quiet = TRUE)
library(CellDestiny)
setwd(getwd())
```

# matrix 1 to 12 months 

```{r , echo=TRUE, warning=FALSE}
# 1) fill parameters 
file_path<-"../patient1_2_3_month1_3_12.csv.gz"
field_separator=","   # if csv==,   if csv2==;   if tsv==\t
file_extention<-".csv.gz"
sampleName_separators="_"
```

```{r , echo=TRUE, warning=FALSE}
# 2) generate your metadata
matrix<-read.csv(file_path, sep = field_separator, check.names=FALSE)
meta<-MakeMetadata(matrix, sampleName_separators)
meta
```

```{r , echo=TRUE, warning=FALSE}
# 3) write the column names than you want 
colnames(meta)<-c("organ", "type", "month", "patient")
meta
```


```{r , echo=TRUE, warning=FALSE}
# 4) export
file_noExtention<-gsub(pattern = file_extention, replacement = "", file_path) # change ".csv" if not .csv file
write.csv(meta, paste0(file_noExtention, "_metadata.csv.gz"), row.names = FALSE, na = "")
```

# 24 months 

```{r , echo=TRUE, warning=FALSE}
# 1) fill parameters 
file_path<-"../patient2_3_month24.csv.gz"
file_noExtention<-gsub(pattern = file_extention, replacement = "", file_path) # change ".csv" if not .csv file
```

```{r , echo=TRUE, warning=FALSE}
# 2) generate your metadata
matrix<-read.csv(file_path, sep = field_separator, check.names=FALSE)
meta<-MakeMetadata(matrix, sampleName_separators)
meta
```

```{r , echo=TRUE, warning=FALSE}
# 3) write the column names than you want 
colnames(meta)<-c("organ", "type", "month", "patient")
meta
# export
write.csv(meta, paste0(file_noExtention, "_metadata.csv.gz"), row.names = FALSE, na = "")
```


